
name: CI:CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            leonardovinicius/rotten-potatoes:latest
            leonardovinicius/rotten-potatoes:${{ github.run_number}}
